# Configuration file for the auto-fetcher wrapper that periodically loads a
# XML file, converts it to a CyberCAPTOR format and sends it to CyberCAPTOR

# Mode :
# remote : fetch the input file from the source_url location
# local : use the local file embedded at local_input_file location
mode: local

# Input :
# gci : expect input file to be at GCI format
# mmt : expect input file to be at MMT format
input: gci

# URL of the server exposing the topology file
#source_url: http://10.99.0.1:9999/gci-report.xml
source_url: http://172.17.22.81:8087/gci-report.txt

# Path for the local report
#local_input_file: /root/cyber-data-extract/examples/gci-report.xml
local_input_file: /root/cyber-data-extract/examples/gci-report2.xml
#local_input_file: /root/cyber-data-extract/examples/mmt-report.xml

# Base URL of the CyberCAPTOR API
#cybercaptor_url: http://10.99.0.1:8080/
cybercaptor_url: http://172.17.22.81:8080/
#cybercaptor_url: http://172.17.22.82:8087/

# delay between consecutive calls, in seconds (default = 120)
delay: 30

